name: guarda_costas_wifi
description: "Um aplicativo completo para segurança e gerenciamento de rede e casa inteligente."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Gerenciamento de Estado
  provider: ^6.1.2

  # Rede e HTTP
  http: ^1.2.1
  web_socket_channel: ^2.4.1
  port_scanner: ^2.0.0 # Para scan de portas

  # Persistência de Dados
  sqflite: ^2.3.2
  path: ^1.9.0
  shared_preferences: ^2.2.2

  # Utilitários e Permissões
  permission_handler: ^11.3.1
  installed_apps: ^1.3.1
  timeago: ^3.6.1 # Para o feed de eventos

  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  # assets:
  #   - assets/apple_health_logo.png
  #   - assets/google_fit_logo.png