name: guarda_costas_wifi
description: "Um aplicativo completo para segurança e gerenciamento de rede e casa inteligente."

# Previne a publicação acidental no pub.dev.
publish_to: 'none' 

# A versão do seu aplicativo.
version: 1.0.0+1

# Configuração do ambiente Dart/Flutter.
environment:
  sdk: '>=3.2.3 <4.0.0'

# Lista de dependências do projeto.
dependencies:
  flutter:
    sdk: flutter

  # --- Gerenciamento de Estado ---
  provider: ^6.1.2

  # --- Rede e HTTP ---
  http: ^1.2.1
  web_socket_channel: ^2.4.1
  lan_scanner: ^2.0.1
  # CORREÇÃO: Versão do pacote atualizada para uma que existe.
  flutter_icmp_ping: ^3.1.3

  # --- Persistência de Dados ---
  sqflite: ^2.3.2
  path: ^1.9.0
  shared_preferences: ^2.2.2

  # --- Utilitários e Permissões ---
  permission_handler: ^11.3.1
  installed_apps: ^1.3.1
  timeago: ^3.6.1

  # --- UI e Ícones ---
  cupertino_icons: ^1.0.2
  
  # --- Dependência de Mapa ---
  flutter_map: ^6.1.0


# Dependências usadas apenas durante o desenvolvimento.
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Ferramenta de análise de código para garantir boas práticas.
  flutter_lints: ^3.0.1

# Configurações específicas do Flutter.
flutter:
  uses-material-design: true