name: guarda_costas_wifi
description: "Um aplicativo completo para segurança e gerenciamento de rede e casa inteligente."

# Previne a publicação acidental no pub.dev.
publish_to: 'none' 

# A versão do seu aplicativo.
version: 1.0.0+1

# Configuração do ambiente Dart/Flutter.
environment:
  sdk: '>=3.2.3 <4.0.0'

# Lista de dependências do projeto.
dependencies:
  flutter:
    sdk: flutter

  # --- Gerenciamento de Estado ---
  # Para gerenciar o estado do aplicativo de forma reativa.
  provider: ^6.1.2

  # --- Rede e HTTP ---
  # Para fazer chamadas a APIs externas (ex: MacVendor).
  http: ^1.2.1
  # Para comunicação em tempo real com o agente no roteador.
  web_socket_channel: ^2.4.1
  # Para a funcionalidade de scan de portas na análise de segurança.
  lan_scanner: ^2.0.1
  # ADICIONADO: Para funcionalidade de ping ICMP (Android Embedding v2 compatível)
  flutter_icmp_ping: ^2.1.2

  # --- Persistência de Dados ---
  # Banco de dados local para salvar dispositivos, eventos, etc.
  sqflite: ^2.3.2
  # Helper para lidar com caminhos de arquivos do sistema.
  path: ^1.9.0
  # Para salvar pequenas configurações do usuário (ex: tema, status de login).
  shared_preferences: ^2.2.2

  # --- Utilitários e Permissões ---
  # Para solicitar permissões do sistema (Localização, Notificações).
  permission_handler: ^11.3.1
  # Para a funcionalidade de listar apps instalados na tela de Segurança do Celular.
  installed_apps: ^1.3.1
  # Para formatar datas de forma amigável (ex: "há 5 minutos") no feed de eventos.
  timeago: ^3.6.1

  # --- UI e Ícones ---
  # Ícones padrão do iOS.
  cupertino_icons: ^1.0.2
  
  # --- Dependência de Mapa ---
  # A dependência 'latlong2' será resolvida automaticamente por este pacote.
  flutter_map: ^6.1.0


# Dependências usadas apenas durante o desenvolvimento.
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Ferramenta de análise de código para garantir boas práticas.
  flutter_lints: ^3.0.1

# Configurações específicas do Flutter.
flutter:
  # Habilita o uso do Material Design.
  uses-material-design: true

  # Seção para declarar assets (imagens, fontes, etc.).
  # Descomente e adicione seus assets aqui quando os tiver.
  # assets:
  #   - assets/images/logo.png
