name: guarda_costas_wifi
description: A Flutter application for WiFi monitoring and coastal guard operations

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  wifi_iot: ^0.3.18
  network_info_plus: ^4.0.2
  permission_handler: ^11.0.1
  geolocator: ^9.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_blue_plus: ^1.14.3
  connectivity_plus: ^5.0.1
  flutter_local_notifications: ^15.1.1
  workmanager: ^0.5.1
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  flutter_map: ^6.0.1
  latlong2: ^0.8.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700