# Nome do fluxo de trabalho
name: Guarda-Costas WIFI

# Gatilhos para iniciar o fluxo de trabalho
on:
  push:
    branches:
      - main # Aciona a cada push para o branch 'main'
  workflow_dispatch: # Permite acionar manualmente pela interface do GitHub

# Trabalhos a serem executados
jobs:
  build:
    # O tipo de máquina virtual que o trabalho será executado
    runs-on: ubuntu-latest

    steps:
      # 1. Clona o seu repositório para a máquina virtual
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configura o ambiente Java (JDK 17), necessário para o Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Configura o ambiente Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6' # Versão específica do Flutter
          channel: 'stable'
          cache: true # Habilita o cache para agilizar builds futuros

      # 4. Limpa o cache do Pub para forçar a leitura dos arquivos mais recentes
      # ESTE É O PASSO CRUCIAL PARA RESOLVER O PROBLEMA DE ARQUIVOS ANTIGOS
      - name: Clean Flutter Project
        run: flutter clean

      # 5. Instala as dependências do projeto a partir do pubspec.yaml
      - name: Install dependencies
        run: flutter pub get

      # 6. Analisa o código para encontrar erros de sintaxe e estilo
      - name: Analyze code
        run: flutter analyze

      # 7. Executa os testes automatizados (se houver)
      - name: Run tests
        run: flutter test

      # 8. Compila o APK de produção (release)
      - name: Build APK Release
        run: flutter build apk --release

      # 9. Compila o AppBundle de produção (release), formato para a Play Store
      - name: Build AppBundle Release
        run: flutter build appbundle --release

      # 10. Faz o upload do APK como um artefato para download
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # 11. Faz o upload do AAB como um artefato para download
      - name: Upload AAB as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab
