name: Build and Release Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Clona o repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configura o JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Configura o ambiente Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'
          cache: true

      # 4. Instala as dependências
      - name: Install dependencies
        run: flutter pub get

      # 5. Analisa o código (opcional)
      - name: Analyze code
        run: flutter analyze

      # 6. Executa os testes (opcional)
      - name: Run tests
        run: flutter test

      # 7. Compila o APK de produção
      - name: Build APK
        run: flutter build apk --release

      # 8. Faz upload do APK gerado
      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
