name: Build and Release Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./guardcostas

      - name: Build APK
        run: flutter build apk --release
        working-directory: ./guardcostas

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: guardcostas/build/app/outputs/flutter-apk/app-release.apk
